services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD) # get the git sha
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1 # disable prompts from google cloud sdk
before_install:
  - pyenv global 3.8.13
  # get the service-account secret (encrypted) and decrypt it. it is stored as a travis-ci secret
  # this line decrypts it and puts file in our project dir. so now we will have a service-account.json file
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  # install google cloud sdk
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  # install kubectl
  - gcloud components update kubectl
  # authenticate to google cloud
  - gcloud auth activate-service-account --key-file service-account.json # auth using service-account.json.enc
  - gcloud config set project multi-k8s-412523 # set project id (from gcloud console)
  - gcloud config set compute/zone us-west2-a # set region (same as one project is deployed)
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin # login to docker
  # build client and run tests
  - docker build -t talfstad/react-test -f ./client/Dockerfile.dev ./client # build test image for client

script:
  - docker run -e CI=true talfstad/react-test npm test # run tests

deploy:
  provider: script # use a custom script for deployment.
  script: bash ./deploy.sh
  on:
    branch: main
