apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: redis
  template: # Pod template
    metadata:
      labels:
        component: redis
    spec:
      containers:
        - name: redis
          image: redis # pulling public repo redis
          ports:
            - containerPort: 6379
          # resources:
          #   limits:
          #     cpu: '0.5'
          #     memory: '512Mi'
