apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: redis
  ports:
    - port: 6379 # expose 6379 on service
      targetPort: 6379 # send traffic to port 6379 on pods
