apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: worker
  template: # Pod template
    metadata:
      labels:
        component: worker
    spec:
      containers:
        - name: worker
          image: talfstad/multi-worker
          # resources:
          #   limits:
          #     cpu: '0.5'
          #     memory: '512Mi'
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
      imagePullSecrets:
        - name: regcred
