apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template: # Pod template
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: talfstad/multi-client
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: regcred
