apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: web
  ports:
    - port: 3000 # expose 3000 on service
      targetPort: 3000 # send traffic to port 3000 on pods
