apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: server
  ports:
    - port: 5000 # expose 5000 on service
      targetPort: 5000 # send traffic to port 5000 on pods
