apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: postgres
  ports:
    - port: 5432 # expose 5432 on service
      targetPort: 5432 # send traffic to port 5432 on pods
